- name: Install Zsh and Oh My Zsh
  hosts: localhost
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - zsh
        state: present

    - name: Install Oh My Zsh
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "/tmp/ohmyzsh_install.sh"
        mode: '0755'  # Make it executable
      notify: Run Oh My Zsh installation script
    
    - name: Change default shell to zsh
      become: true
      ansible.builtin.command:
        cmd: chsh -s $(which zsh) {{ ansible_user_id }}
      args:
        creates: "{{ ansible_env.HOME }}/.zshrc"

- handlers:
  - name: Run Oh My Zsh installation script
    ansible.builtin.command: "/usr/bin/sh /tmp/ohmyzsh_install.sh --unattended"
    args:
      creates: "/root/.oh-my-zsh"
