---
- name: Install Zsh and Oh My Zsh
  hosts: localhost
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - zsh
          - curl
        state: present

    - name: Install Oh My Zsh
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "/tmp/ohmyzsh_install.sh"
        mode: '0755'  # Make it executable
      register: download_script

    # - name: Run Oh My Zsh installation script
    #   ansible.builtin.shell: "/bin/bash /tmp/ohmyzsh_install.sh --unattended"
    #   args:
    #     creates: "/root/.oh-my-zsh"
    #   when: download_script.changed
    #   notify: Install Oh My Zsh

    - name: Change default shell to zsh
      become: true
      ansible.builtin.command:
        cmd: chsh -s /bin/zsh {{ ansible_user_id }}
      args:
        creates: "{{ ansible_env.HOME }}/.zshrc"

  # Handler to run the installation script
  handlers:
    - name: Install Oh My Zsh
      ansible.builtin.command: "/usr/bin/bash /tmp/ohmyzsh_install.sh --unattended"
      args:
        creates: "~/.oh-my-zsh"
