- name: Install Zsh and Oh My Zsh
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.package:
        name:
          - zsh
        state: present

    - name: Pull down dotfiles
      ansible.builtin.git:
        repo: https://github.com/nathan-stamand/dotfiles/
        dest: "{{ ansible_env.HOME }}/dotfiles"
        version: main

    - name: Pull down powerlevel10k
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k/
        dest: "{{ ansible_env.HOME }}/powerlevel10k"
        version: master

    - name: Ensure dotfiles scripts are executable
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/dotfiles/scripts"
        mode: '0755'
        recurse: true
        state: directory

    - name: Set up .config/alacritty symlink
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/dotfiles/alacritty"
        dest: "{{ ansible_env.HOME }}/.config/alacritty"
        state: link

    - name: Set up powerlevel10k config symlink
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/dotfiles/.p10k.zsh"
        dest: "{{ ansible_env.HOME }}/.p10k.zsh"
        state: link

    - name: Set up .config/tms symlink
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/dotfiles/tms"
        dest: "{{ ansible_env.HOME }}/.config/tms"
        state: link

    - name: Set up tmux.conf symlink
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/dotfiles/.tmux.conf"
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
        state: link

    - name: Set up .zsh_functions symlink
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/dotfiles/zsh/.zsh_functions"
        dest: "{{ ansible_env.HOME }}/.zsh_functions"
        state: link

    - name: Set up .zshenv symlink
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/dotfiles/zsh/.zshenv"
        dest: "{{ ansible_env.HOME }}/.zshenv"
        state: link

    - name: Install Oh My Zsh
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "/tmp/ohmyzsh_install.sh"
        mode: '0755'  # Make it executable

    - name: Run Oh My Zsh installation script
      ansible.builtin.command: "/usr/bin/sh /tmp/ohmyzsh_install.sh --unattended"
      args:
        creates: "/root/.oh-my-zsh"

    - name: Set up .zshrc symlink
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/dotfiles/zsh/.zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc"
        state: link

    - name: Get current shell
      ansible.builtin.command: "getent passwd {{ ansible_user_id }}"
      register: passwd_entry
      changed_when: false

    - name: Set current shell fact
      ansible.builtin.set_fact:
        current_shell: "{{ passwd_entry.stdout.split(':')[-1] }}"

    - name: Change default shell to zsh if not already
      become: true
      ansible.builtin.command: "chsh -s /usr/bin/zsh {{ ansible_user_id }}"
      when: current_shell != '/usr/bin/zsh'
      changed_when: true
